var script = document.createElement('script');
script.innerHTML = " var g_isipad = true; " +
"  var  g_videoClipTag = 'alt-video-clip';  "+
"   function init() { " +
"	_util = new Util();" + 
"	_console = new Console();" +
"	_search = new Search();" +
"	_browse = new Browse('Browse');" +
"	_whatshot = new Browse('WhatsHot','hotvideos_1');" +
"	_whatsnew = new Browse('WhatsNew','newvideos',true); " +
"	_details = new Details();" + 
"	_highlight = new Highlight();" +
"	_liveevent = new LiveEvent();" +
"	_podcast = new Podcast();" +
"	_channel = new Channel();" +
"	_gameday = new GameDay();" +
"	document.getElementById('ipadPlayer').style.display='';" +
"	iptvComplete(); } " +
" function iptvComplete() "+
" { " +
' var ads = [{id:"topImg",iframe:'+
'"http://ad.doubleclick.net/adi/nhl.tv/mainvideo;pos=leader;tile=4;sz=728x90"'+
'}];'+
'var menus = [' +
'{index:0,type:100,id:-3,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/gamehighlights.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/gamehighlights.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/gamehighlights.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/gamehighlights.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/gamehighlights.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:1,type:1,id:35,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/quickpicks.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/quickpicks.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/quickpicks.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/quickpicks.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/quickpicks.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:2,type:1,id:53,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/sound.tv/mainvideo;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/sound.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/sound.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/sound.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/adj/sound.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:3,type:1,id:17,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/best.tv/mainvideo;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/best.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/best.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/best.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/best.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:4,type:1,id:40,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/pregame.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/pregame.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/pregame.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/pregame.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/pregame.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:5,type:1,id:54,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/fantasy.tv/mainvideo;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/fantasy.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/fantasy.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/fantasy.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/fantasy.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:6,type:1,id:34,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/shootout.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/shootout.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/shootout.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/shootout.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/shootout.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:7,type:0,id:1083,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/adj/seasonal.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/jump/seasonal.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:8,type:0,id:618,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/nhllibrary.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/nhllibrary.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/nhllibrary.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/nhllibrary.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/nhllibrary.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:9,type:4,id:616,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/pressroom.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/pressroom.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/pressroom.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/pressroom.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/pressroom.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:10,type:0,id:635,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/draft.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/draft.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/draft.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/draft.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/draft.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:11,type:0,id:1043,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/finest.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/finest.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/finest.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/adj/finest.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/jump/finest.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:12,type:1,id:48,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"",first:"",subsequent:""},link:"",imgSrc:""},'+
'{index:13,type:5,id:-4,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/podcast.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/podcast.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/podcast.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/podcast.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/podcast.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:14,type:1,id:14,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/winterclassic.tv/mainvideo;pos=billboard;sz=480x270;tile=5",first:"http://ad.doubleclick.net/pfadx/winterclassic.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/winterclassic.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/winterclassic.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/winterclassic.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:15,type:0,id:1081,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/seasonal.tv/mainvideo;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/adj/seasonal.tv/mainvideo;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/jump/seasonal.tv/mainvideo;pos=leader;tile=4;sz=728x90"},'+
'{index:-2,type:6,id:-7,adIntervalType:0,adInterval:150,playedFirstVideoDefault:true,adTags:{adServer:0,acudeoProgram:"",billboard:"http://ad.doubleclick.net/pfadx/nhl.tv/hotclips;pos=billboard;sz=480x270;tile=3",first:"http://ad.doubleclick.net/pfadx/nhl.tv/hotclips;pos=videoplay;sz=480x270;tile=1",subsequent:"http://ad.doubleclick.net/pfadx/nhl.tv/hotclips;pos=videoplay2;sz=480x270;tile=2"},link:"http://ad.doubleclick.net/jump/nhl.tv/hotclips;pos=leader;tile=4;sz=728x90",imgSrc:"http://ad.doubleclick.net/ad/nhl.tv/hotclips;pos=leader;tile=4;sz=728x90"}'+
'];'+
'var isCanada = false;'+
'var isUSA = false;'+
'var locAudioSlideshow = "http://nhl.neulion.net/u/www/audio/";'+
'processDeepLinking();'+
'}';

document.body.insertBefore(script,document.body.firstChild);